name: Docker

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  get-sdk:
    name: Get latest Windows SDK
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: windows-sdk-cache
      with:
        path: WindowsSDK.7z
        key: WindowsSDK.7z
    - name: List Windows SDKs
      run: |
        # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
        dir "C:\Program Files (x86)\Windows Kits\10"
        dir "C:\Program Files (x86)\Windows Kits\10\Include"
        dir "C:\Program Files (x86)\Windows Kits\10\Lib"
    - name: Get Windows SDK
      if: steps.windows-sdk-cache.outputs.cache-hit != 'true'
      run: |
        mkdir WindowsSDK\VC\Tools\MSVC
        mkdir "WindowsSDK\Windows Kits\10\Include"
        mkdir "WindowsSDK\Windows Kits\10\Lib"
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK" WindowsSDK /E /I /H
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130" WindowsSDK\VC\Tools\MSVC /E /I /H
        xcopy "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0" "WindowsSDK\Windows Kits\10\Include" /E /I /H
        xcopy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0" "WindowsSDK\Windows Kits\10\Lib" /E /I /H
        7z a WindowsSDK.7z WindowsSDK\
        dir
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: WindowsSDK.7z
        name: WindowsSDK
