name: Docker

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  get-sdk:
    name: Get latest Windows SDK
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: windows-sdk-cache
      with:
        path: WindowsSDK.7z
        key: WindowsSDK.7z
    - name: List Windows SDKs
      run: |
        # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC"
        tree "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC"
        dir "C:\Program Files (x86)\Windows Kits\10"
        dir "C:\Program Files (x86)\Windows Kits\10\Include"
        dir "C:\Program Files (x86)\Windows Kits\10\Lib"
        dir "C:\Program Files (x86)\Windows Kits\10\bin"
        dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\ucrt"
        tree "C:\Program Files (x86)\Windows Kits\10\bin"
    - name: Get Windows SDK
      if: steps.windows-sdk-cache.outputs.cache-hit != 'true'
      run: |
        mkdir WindowsSDK\VC\Tools\MSVC
        mkdir "WindowsSDK\Windows Kits\10\Include"
        mkdir "WindowsSDK\Windows Kits\10\Lib"
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK" "WindowsSDK\DIA SDK\" /E /I /H /Q
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130" "WindowsSDK\VC\Tools\MSVC\14.38.33130\" /E /I /H /Q
        xcopy "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0" "WindowsSDK\Windows Kits\10\Include\10.0.22621.0\" /E /I /H /Q
        xcopy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0" "WindowsSDK\Windows Kits\10\Lib\10.0.22621.0\" /E /I /H /Q
        7z a WindowsSDK.7z WindowsSDK\
        dir
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        overwrite: true
        path: WindowsSDK.7z
        name: WindowsSDK
