name: Test

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  list-sdk:
    name: List installed SDK
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: List SDKs
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
        dir "C:\Program Files (x86)\Windows Kits\10"
        dir "C:\Program Files (x86)\Windows Kits\10\Include"
        dir "C:\Program Files (x86)\Windows Kits\10\Lib"
        mkdir WindowsSDK\VC\Tools
        mkdir "WindowsSDK\Windows Kits\10"
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK" WindowsSDK /E /I /H
        xcopy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC" WindowsSDK\VC\Tools /E /I /H
        xcopy "C:\Program Files (x86)\Windows Kits\10\Include" "WindowsSDK\Windows Kits\10" /E /I /H
        xcopy "C:\Program Files (x86)\Windows Kits\10\Lib" "WindowsSDK\Windows Kits\10" /E /I /H
        7z a WindowsSDK.7z WindowsSDK\
        dir
    
